// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEALoOy02nEKNOXVyAs5z1oAqh5P1mU68',
    appId: '1:232322215697:web:9397020dc19f4188fee6b0',
    messagingSenderId: '232322215697',
    projectId: 'deque-b6a64',
    authDomain: 'deque-b6a64.firebaseapp.com',
    storageBucket: 'deque-b6a64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASpGVjkuqJvD9AKvFJNsXWW12mC3A7RLY',
    appId: '1:232322215697:android:0945e40055ebfd38fee6b0',
    messagingSenderId: '232322215697',
    projectId: 'deque-b6a64',
    storageBucket: 'deque-b6a64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ljssehOSE-LSaymu6CGEl5DM2ZUU5kI',
    appId: '1:232322215697:ios:11744967b7961a0ffee6b0',
    messagingSenderId: '232322215697',
    projectId: 'deque-b6a64',
    storageBucket: 'deque-b6a64.appspot.com',
    iosClientId: '232322215697-kqhhndhpo9m7unj4p33gtjad0hb9fsa9.apps.googleusercontent.com',
    iosBundleId: 'com.example.deque',
  );
}
